---
apiVersion: tower.ansible.com/v1alpha1
kind: AnsibleJob
metadata:
  name: rhacm-prehook-open-snow-ticket
  namespace: simpleweb
  labels:
    app.kubernetes.io/name: simpleweb
spec:
  tower_auth_secret: toweraccess
  job_template_name: rhacm_prehook_open_snow_ticket
  extra_vars:
    app_name: simpleweb
    message: "Updated by Red Hat Advanced Cluster Management for Kubernetes"
