
---
apiVersion: tower.ansible.com/v1alpha1
kind: AnsibleJob
metadata:
  name: rhacm-posthook-create-dns-record
  namespace: simpleweb
  labels:
    app.kubernetes.io/name: simpleweb
spec:
  tower_auth_secret: toweraccess
  job_template_name: rhacm_posthook_create_dns_record
  extra_vars:
    app_name: simpleweb
    godaddy_dns_record_name: simpleweb
    godaddy_domain: rsoliman.com
    service_route: simpleweb-simpleweb.apps.rsoliman-ocp.mydemo.run
    message: "Updated by Red Hat Advanced Cluster Management for Kubernetes"
